export const POWER_PLANTS = [
  // HYDRO
  { id: "hydro-alqueva", name: "Alqueva Dam", countryCode: "PT", type: "Hydro", coordinates: [38.1961, -7.4983], capacityMW: 520, annualProductionTWh: 0.3, curiosity: "Creates the largest artificial lake in Western Europe.", image: "https://images.impresa.pt/expresso/2022-02-06-alqueva-dam/original" },
  { id: "hydro-grandmaison", name: "Grand'Maison", countryCode: "FR", type: "Hydro", coordinates: [45.2236, 6.1158], capacityMW: 1800, annualProductionTWh: 1.42, curiosity: "The most powerful hydroelectric power plant in France.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6gqiF3vt6fnoNzUQQOBbqXCw0Lmhsi7CY6g&s" },
  { id: "hydro-aldeadavila", name: "Aldeadávila", countryCode: "ES", type: "Hydro", coordinates: [41.2091, -6.6852], capacityMW: 1243, annualProductionTWh: 2.4, curiosity: "Built in the Douro River canyon on the border with Portugal.", image: "https://media-cdn.tripadvisor.com/media/photo-c/1280x250/10/95/3e/46/dsc-2833-largejpg.jpg" },
  { id: "hydro-karahnjukar", name: "Kárahnjúkar", countryCode: "IS", type: "Hydro", coordinates: [64.9358, -15.7925], capacityMW: 690, annualProductionTWh: 4.6, curiosity: "Exclusively powers a gigantic aluminum smelter.", image: "https://upload.wikimedia.org/wikipedia/commons/b/b9/K%C3%A1rahnj%C3%BAkar_dam_08.jpg" },
  { id: "hydro-iron-gate", name: "Iron Gate I", countryCode: "RO", type: "Hydro", coordinates: [44.6722, 22.5283], capacityMW: 2253, annualProductionTWh: 11.3, curiosity: "The largest dam on the Danube River, shared with Serbia.", image: "https://www.stojanovic-hydro.com/wp-content/uploads/2022/06/hydropower.jpg" },

  // NUCLEAR
  { id: "nuc-olkiluoto", name: "Olkiluoto", countryCode: "FI", type: "Nuclear", coordinates: [61.2355, 21.4402], capacityMW: 3380, annualProductionTWh: 24.5, curiosity: "Reactor 3 is the largest in Europe and covers 30% of Finland's energy.", image: "https://www.nsenergybusiness.com/wp-content/uploads/sites/4/2022/01/Image-1-Olkiluoto-Nuclear-Power-Plant.jpg" },
  { id: "nuc-zaporizhzhia", name: "Zaporizhzhia", countryCode: "UA", type: "Nuclear", coordinates: [47.5111, 34.5861], capacityMW: 5700, annualProductionTWh: 38.0, curiosity: "The largest nuclear power plant in Europe (currently under containment).", image: "https://www.power-technology.com/wp-content/uploads/sites/21/2017/09/Image-4L-1.jpg" },
  { id: "nuc-gravelines", name: "Gravelines", countryCode: "FR", type: "Nuclear", coordinates: [51.0136, 2.1366], capacityMW: 5460, annualProductionTWh: 38.4, curiosity: "Uses the North Sea to cool its 6 reactors.", image: "https://s.rfi.fr/media/display/31c89a40-8235-11ef-9870-005056a90284/w:1280/p:16x9/Gravelines_Nuclear_Power_Station.jpg" },
  { id: "nuc-krsko", name: "Krško", countryCode: "SI", type: "Nuclear", coordinates: [45.9380, 15.5266], capacityMW: 696, annualProductionTWh: 5.4, curiosity: "Co-owned by Slovenia and Croatia, it covers 20% of Slovenian consumption.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqcJ0hrj9dr7fbptY2fR0jopVbK91_fz3uJw&s" },

  // WIND
  { id: "wind-hornsea", name: "Hornsea Project 1", countryCode: "UK", type: "Wind Offshore", coordinates: [53.8833, 1.1500], capacityMW: 1218, annualProductionTWh: 4.5, curiosity: "One of the largest offshore wind farms in the world.", image: "https://www.nsenergybusiness.com/wp-content/uploads/sites/4/2018/10/2l-Image-Hornsea-Offshore-Wind-Project.jpg" },
  { id: "wind-gemini", name: "Gemini Wind Farm", countryCode: "NL", type: "Wind Offshore", coordinates: [54.0333, 5.9666], capacityMW: 600, annualProductionTWh: 2.6, curiosity: "Invisible from the coast, located 85 km from the mainland.", image: "https://www.energymonitor.ai/wp-content/uploads/sites/2/2024/11/Image-3-Gemini-Offshore-Wind-Farm.jpg" },
  { id: "wind-markbygden", name: "Markbygden", countryCode: "SE", type: "Wind Onshore", coordinates: [65.3400, 20.8000], capacityMW: 1123, annualProductionTWh: 3.3, curiosity: "Ongoing project that will be the largest onshore wind farm in Europe.", image: "https://cached.imagescaler.hbpl.co.uk/resize/scaleWidth/1272/cached.offlinehbpl.hbpl.co.uk/news/OPW/SvevindMarkbygden.png" },
  { id: "wind-fantanele", name: "Fântânele-Cogealac", countryCode: "RO", type: "Wind Onshore", coordinates: [44.5833, 28.5500], capacityMW: 600, annualProductionTWh: 1.5, curiosity: "The largest onshore wind farm in the EU at the time of its construction.", image: "https://www.power-technology.com/wp-content/uploads/sites/21/2017/09/1l-image-52.jpg" },

  // SOLAR
  { id: "sol-nunez-balboa", name: "Núñez de Balboa", countryCode: "ES", type: "Solar", coordinates: [38.4350, -6.2088], capacityMW: 500, annualProductionTWh: 0.8, curiosity: "Supplies the equivalent of 250,000 homes per year.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6Yoa-_YubzfpQxbkZLS4YEJ6wKRUyz1bnSA&s" },
  { id: "sol-cestas", name: "Cestas Solar Park", countryCode: "FR", type: "Solar", coordinates: [44.7233, -0.8250], capacityMW: 300, annualProductionTWh: 0.35, curiosity: "Panels oriented at an innovative east-to-west angle.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbROAzZWCRQNciVfhp3AbyDGTRuI0HXSR5oQ&s" },
  { id: "sol-karapinar", name: "Karapınar", countryCode: "TR", type: "Solar", coordinates: [37.7833, 33.6000], capacityMW: 1350, annualProductionTWh: 2.5, curiosity: "More than 3.2 million panels in a desert area.", image: "https://images.euronews.com/articles/stories/09/71/45/02/1536x864_cmsv2_cda50318-a520-524c-9c32-0b8a181ec240-9714502.jpg" },

  // THERMAL
  { id: "therm-belchatow", name: "Bełchatów", countryCode: "PL", type: "Thermal", coordinates: [51.2661, 19.3305], capacityMW: 5102, annualProductionTWh: 32.3, curiosity: "The largest coal-fired power plant in Europe, responsible for 20% of Polish energy.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNq_aI9n4ZYlcRl-3udyBQDOigB5jf57N3Mg&s" },
  { id: "therm-neurath", name: "Neurath", countryCode: "DE", type: "Thermal", coordinates: [51.0380, 6.6111], capacityMW: 4211, annualProductionTWh: 26.0, curiosity: "Enormous lignite power plant; a central focus in transition debates.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDaIuldkFca-1ByK9Gje_zvP0MnFU_3Wq7kQ&s" },
  { id: "therm-drax", name: "Drax Power Station", countryCode: "UK", type: "Thermal", coordinates: [53.7369, -0.9972], capacityMW: 3906, annualProductionTWh: 14.0, curiosity: "Converted from coal to biomass, it is the largest renewable power station in the UK.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3Lnamvmzap_dACIXAs5YtxwQlDOwi3RbMGQ&s" }
];